### ISSUE TITLE
create demo version of the repository as a separate (permanent?) branch

### ISSUE THREAD

**Issue by trentwirth** [HuMoN-Research-Lab/AR_GroundPlane#21]
it would be good to have a basic demo version of the experiment where  I could show off the "difficulty" of the task in order to a visitor

**Comment by jonmatthis** [comment]
What you're describing here is more akin to a 'Release' than a 'Branch' 

Basically, once you're got things  on `main` in a place where it's good as a demo, you can make a 'release' on Github that will freeze things where there are so you can always grab it in that form. 

'branches' aren't supposed to be permanent
