### ISSUE TITLE
write python code to generate terrain json file

### ISSUE THREAD

**Issue by trentwirth** [HuMoN-Research-Lab/AR_GroundPlane#22]

**Comment by jonmatthis** [comment]
Remember - `json`'s are just Python `dictionaries` 

... which is to say, you just need to build your terrain out as a `dict` and then save that out to  a `json` using `json.dumps` or something: 

https://www.geeksforgeeks.org/how-to-convert-python-dictionary-to-json/

**Comment by trentwirth** [comment]
deferring this until the next iteration of the ARGP...
